### ISSUE TITLE
download speed trouble

### ISSUE THREAD

**Issue by 24802** [chinponya/asset_janny#1]
download speed seems to have slowed down a lot these days. Is it a problem with the majsoul server?

**Comment by chinponya** [comment]
You can try increasing the amount of parallel download jobs with the `--jobs` flag. I changed the default to 1 at some point, which made it a lot slower.
The reason was that I found the servers would sometimes IP ban clients for like an hour, even with just 2 jobs. When it appears like the program got stuck on a download forever, that's probably what happened.

**Comment by chinponya** [comment]
Actually, as I was testing if it still IP bans me, I found that at some point this flag was broken and always defaulted to 1. I've published a new version with a fix.
Also, I didn't get banned yet, so maybe it's not an issue anymore?

**Comment by 24802** [comment]
I checked that ip ban exists It actually works fine with vpn and new release version ty for the update
